// <auto-generated />
using System;
using EdgeFront.Builder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdgeFront.Builder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305001853_AddSessionPresentersAndCoordinators")]
    partial class AddSessionPresentersAndCoordinators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.NormalizedAttendance", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DurationPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FirstJoinAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLeaveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttendanceId");

                    b.HasIndex("SessionId", "EmailDomain");

                    b.HasIndex("OwnerUserId", "SessionId", "Email")
                        .IsUnique();

                    b.ToTable("NormalizedAttendances");
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.NormalizedRegistration", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegistrationId");

                    b.HasIndex("SessionId", "EmailDomain");

                    b.HasIndex("OwnerUserId", "SessionId", "Email")
                        .IsUnique();

                    b.ToTable("NormalizedRegistrations");
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.Series", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SeriesId");

                    b.HasIndex("OwnerUserId", "CreatedAt");

                    b.HasIndex("OwnerUserId", "Title")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.SeriesMetrics", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalAttendees")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegistrations")
                        .HasColumnType("int");

                    b.Property<int>("UniqueAccountsInfluenced")
                        .HasColumnType("int");

                    b.Property<int>("UniqueRegistrantAccountDomains")
                        .HasColumnType("int");

                    b.Property<string>("WarmAccounts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeriesId");

                    b.ToTable("SeriesMetrics");
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriftStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JoinWebUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReconcileStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Synced");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamsWebinarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.HasIndex("SeriesId", "StartsAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.SessionCoordinator", b =>
                {
                    b.Property<Guid>("SessionCoordinatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntraUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionCoordinatorId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "EntraUserId")
                        .IsUnique();

                    b.ToTable("SessionCoordinators");
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.SessionMetrics", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalAttendees")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegistrations")
                        .HasColumnType("int");

                    b.Property<int>("UniqueAttendeeAccountDomains")
                        .HasColumnType("int");

                    b.Property<int>("UniqueRegistrantAccountDomains")
                        .HasColumnType("int");

                    b.Property<string>("WarmAccountsTriggered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("SessionMetrics");
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.SessionPresenter", b =>
                {
                    b.Property<Guid>("SessionPresenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntraUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionPresenterId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "EntraUserId")
                        .IsUnique();

                    b.ToTable("SessionPresenters");
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.NormalizedAttendance", b =>
                {
                    b.HasOne("EdgeFront.Builder.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.NormalizedRegistration", b =>
                {
                    b.HasOne("EdgeFront.Builder.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.SeriesMetrics", b =>
                {
                    b.HasOne("EdgeFront.Builder.Domain.Entities.Series", null)
                        .WithOne()
                        .HasForeignKey("EdgeFront.Builder.Domain.Entities.SeriesMetrics", "SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.Session", b =>
                {
                    b.HasOne("EdgeFront.Builder.Domain.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.SessionCoordinator", b =>
                {
                    b.HasOne("EdgeFront.Builder.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.SessionMetrics", b =>
                {
                    b.HasOne("EdgeFront.Builder.Domain.Entities.Session", null)
                        .WithOne()
                        .HasForeignKey("EdgeFront.Builder.Domain.Entities.SessionMetrics", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdgeFront.Builder.Domain.Entities.SessionPresenter", b =>
                {
                    b.HasOne("EdgeFront.Builder.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
